### ISSUE TITLE
Problem reading checksum, not a stream?

### ISSUE THREAD

**Issue by marcohamersma** [FormidableLabs/rapscallion#61]
In the [example](https://github.com/FormidableLabs/rapscallion#example), It is implied that with the following code, one should be able to set the react checksum.

```js
const componentRenderer = render(<MyComponent store={store} />);

template`
  document.querySelector("#id-for-component-root").setAttribute("data-react-checksum", "${componentRenderer.checksum()}")
`.
```

For me, this leads to an error: `Renderer#checksum can only be invoked for a renderer converted to node stream.`. 

This seems to be an inconsistency. However if I append `toStream()` to `componentRenderer`, I get another error: 

`Unknown value in template of type object: [object Object] at getSequenceEvent (/Users/…node_modules/rapscallion/lib/template.js:33:11)`.

If I get the checksum by doing `componentRenderer.toStream().checksum()` it ends up being empty `""`.

Is there something I'm doing wrong? or is this an issue with rapscallion or its documentation/

**Comment by divmain** [comment]
I believe this was a regression.  I'll have a fix (and regression test) out for this tomorrow @marcohamersma.  Thanks for the report!

**Comment by tom2strobl** [comment]
Hi there, are there any updates? I'm also down for an ungly hack in the meantime – can't get the checksum running in any way somehow.

**Comment by tom2strobl** [comment]
@divmain I tried to get the `.checksum()` from the responseRenderer, but that obviously doesn't work. Then I tried to call `componentRenderer.toStream()` manually, but that's not getting anywhere either. The componentRenderer lacks `this._stream`, but I have no idea how it should get one if I can't call `toStream()`.
Does it mean currently you can't get the checksum feature if you use the `responseRenderer`?

**Comment by divmain** [comment]
@tom2strobl @marcohamersma Sorry for the delay on this.  Real life interrupted :).  Fix is in master and published to `rapscallion@next`.  Would one of you be willing to install and check that this is resolved for you?

**Comment by tom2strobl** [comment]
No worries, this is Open Source and you're doing it for free so there can't be a _delay_ :-)
I tried `npm i -S rapscallion@next` which installed `2.1.2`, unfortunately it seems to still persist, here's my (shortened) use case:

```javascript
const componentRenderer = render(<Component {...data} />);
const responseRenderer = template`
  // [...]
  <div id="app-mount">${componentRenderer}</div>
  // [...]
  <script id="app-state">
    window.state = ${() => JSON.stringify(data)}
    document.querySelector("#app-mount").setAttribute("data-react-checksum", "${componentRenderer.checksum()}")
  </script>
`;
const stream = responseRenderer.toStream();
// "this" is in that case a hapi reply interface, so don't worry about it – that part works
this(stream);
```

It throws:
```
2017-03-15/10:27:03:041, [error] message: Renderer#checksum can only be invoked for a renderer converted to node stream. stack: Error: Renderer#checksum can only be invoked for a renderer converted to node stream.
    at Renderer.checksum (/.../node_modules/rapscallion/lib/renderer.js:56:15)
```

Am I using it wrong?

**Comment by divmain** [comment]
So... I may have forgotten to `npm run build` before publishing 🔨 Try it now, you should see `v2.1.3` available under the `next` tag.

**Comment by tom2strobl** [comment]
Interesting, it now throws
```
    TypeError: Cannot read property 'toString' of undefined
    at Renderer.checksum (/.../node_modules/rapscallion/lib/renderer.js:82:28)
```

**Comment by HugoGiraudel** [comment]
Seconded. 2.1.1 throws ` Renderer#checksum can only be invoked for a renderer converted to node stream.`, 2.1.3 throws `Cannot read property 'toString' of undefined`.

**Comment by divmain** [comment]
Can one of you throw up a gist that reproduces? I nerd something to work against.

**Comment by bmathews** [comment]
I believe the template is supposed to be:
```${() => componentRenderer.checksum()}```

instead of:
```${componentRenderer.checksum()}```

**Comment by divmain** [comment]
Shoot, the docs are wrong.  Thank you for pointing that out @bmathews.  I'll fix that in my branch.

**Comment by mattiasewers** [comment]
@bmathews this and `v2.1.3`  solved the problem for me

**Comment by divmain** [comment]
Thanks everybody.  I move these changes into master and publish to `latest`.
